### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [tadmint/prj-rev-bwfs-dasmoto#1]
Alternatively, you can specify shared properties for multiple elements by including all the selectors separated by commas:

```css
h1, h2, .price {
  font-weight: bold;
}
```

https://github.com/tadmint/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/style.css
